Repository microsoftwo/be14-2nd-microsoftwo-clother, pull requests merged in 2025-03, with the labels that each got.

#4 [feat] 프로젝트 패키지 구조 설정
  src/main/java/com/microsoftwo/clother/post/command/application/controller/ex
  src/main/java/com/microsoftwo/clother/post/command/application/dto/ex
  src/main/java/com/microsoftwo/clother/post/command/application/service/ex
  src/main/java/com/microsoftwo/clother/post/command/domain/aggregate/ex
  src/main/java/com/microsoftwo/clother/post/command/domain/repository/ex
  src/main/java/com/microsoftwo/clother/post/command/domain/service/ex
  src/main/java/com/microsoftwo/clother/post/command/infrastructure/service/ex
  src/main/java/com/microsoftwo/clother/post/query/controller/ex
  src/main/java/com/microsoftwo/clother/post/query/dao/ex
  src/main/java/com/microsoftwo/clother/post/query/service/ex
Labels: 🧺 chore, 🚘 feature

#11 [chore] gitignore 수정
  .gitignore
Labels: 🧺 chore

#20 [feat] 피드 최신순 조회
  src/main/java/com/microsoftwo/clother/post/query/controller/PostController.java
  src/main/java/com/microsoftwo/clother/post/query/dao/PostMapper.java
  src/main/java/com/microsoftwo/clother/post/query/dto/PostForFeedDTO.java
  src/main/java/com/microsoftwo/clother/post/query/service/PostService.java
  src/main/java/com/microsoftwo/clother/post/query/service/PostServiceImpl.java
  src/main/resources/com/microsoftwo/clother/post/query/dao/PostMapper.xml
Labels: 🚘 feature

#9 [feat] 포스팅 상세 조회 기능 구현
  src/main/java/com/microsoftwo/clother/config/PostConfig.java
  src/main/java/com/microsoftwo/clother/post/query/controller/PostController.java
  src/main/java/com/microsoftwo/clother/post/query/controller/ex
  src/main/java/com/microsoftwo/clother/post/query/dao/PostMapper.java
  src/main/java/com/microsoftwo/clother/post/query/dao/ex
  src/main/java/com/microsoftwo/clother/post/query/dto/HairTagDTO.java
  src/main/java/com/microsoftwo/clother/post/query/dto/PostAndHairTagDTO.java
  src/main/java/com/microsoftwo/clother/post/query/dto/PostDTO.java
  src/main/java/com/microsoftwo/clother/post/query/dto/PostForFeedDTO.java
  src/main/java/com/microsoftwo/clother/post/query/dto/ProductTagDTO.java
  src/main/java/com/microsoftwo/clother/post/query/service/PostService.java
  src/main/java/com/microsoftwo/clother/post/query/service/PostServiceImpl.java
  src/main/java/com/microsoftwo/clother/post/query/service/ex
  src/main/java/com/microsoftwo/clother/post/query/vo/ResponsePostVO.java
  src/main/resources/com/microsoftwo/clother/post/query/dao/PostMapper.xml
Labels: 🚘 feature

#13 [feat] 게시판 조회 구현
  src/main/java/com/microsoftwo/clother/adviceBoard/query/controller/BoardQueryController.java
  src/main/java/com/microsoftwo/clother/adviceBoard/query/dao/BoardMapper.java
  src/main/java/com/microsoftwo/clother/adviceBoard/query/dto/BoardDTO.java
  src/main/java/com/microsoftwo/clother/adviceBoard/query/service/BoardQueryService.java
  src/main/resources/com/microsoftwo/clother/adviceBoard/query/dao/BoardMapper.xml
Labels: 🚘 feature

#15 [feat] 카테고리 전체 목록 조회 구현
  src/main/java/com/microsoftwo/clother/config/ProductConfig.java
  src/main/java/com/microsoftwo/clother/product/command/application/controller/ex
  src/main/java/com/microsoftwo/clother/product/command/application/dto/ex
  src/main/java/com/microsoftwo/clother/product/command/application/service/ex
  src/main/java/com/microsoftwo/clother/product/command/domain/aggregate/ex
  src/main/java/com/microsoftwo/clother/product/command/domain/repository/ex
  src/main/java/com/microsoftwo/clother/product/command/domain/service/ex
  src/main/java/com/microsoftwo/clother/product/command/infrastructure/service/ex
  src/main/java/com/microsoftwo/clother/product/query/controller/ProductController.java
  src/main/java/com/microsoftwo/clother/product/query/dto/CategoryDTO.java
  src/main/java/com/microsoftwo/clother/product/query/dto/ProductCategoryDTO.java
  src/main/java/com/microsoftwo/clother/product/query/dto/ProductDetailDTO.java
  src/main/java/com/microsoftwo/clother/product/query/dto/ProductRegistHistoryDTO.java
  src/main/java/com/microsoftwo/clother/product/query/repository/ProductMapper.java
  src/main/java/com/microsoftwo/clother/product/query/service/ProductService.java
  src/main/java/com/microsoftwo/clother/product/query/service/ProductServiceImpl.java
  src/main/resources/com/microsoftwo/clother/product/query/repository/ProductMapper.xml
Labels: 🚘 feature

#23 [chore] eureka-server 프로젝트 추가
  eureka-server/.gitattributes
  eureka-server/.gitignore
  eureka-server/build.gradle
  eureka-server/gradle/wrapper/gradle-wrapper.jar
  eureka-server/gradle/wrapper/gradle-wrapper.properties
  eureka-server/gradlew
  eureka-server/gradlew.bat
  eureka-server/settings.gradle
  eureka-server/src/main/java/com/microsoftwo/eurekaserver/EurekaServerApplication.java
  eureka-server/src/test/java/com/microsoftwo/eurekaserver/EurekaServerApplicationTests.java
Labels: 🧺 chore

#25 [chore] gateway-server 초기 세팅
  gateway-server/.gitattributes
  gateway-server/.gitignore
  gateway-server/build.gradle
  gateway-server/gradle/wrapper/gradle-wrapper.jar
  gateway-server/gradle/wrapper/gradle-wrapper.properties
  gateway-server/gradlew
  gateway-server/gradlew.bat
  gateway-server/settings.gradle
  gateway-server/src/main/java/com/microsoftwo/gatewayserver/GatewayServerApplication.java
  gateway-server/src/test/java/com/microsoftwo/gatewayserver/GatewayServerApplicationTests.java
Labels: 🧺 chore

#33 [feat] 사용자의 상품 등록 신청 구현
  core-service/build.gradle
  core-service/src/main/java/com/microsoftwo/clother/Be142ndMicrosoftwoClotherApplication.java
  core-service/src/main/java/com/microsoftwo/clother/config/AppConfig.java
  core-service/src/main/java/com/microsoftwo/clother/config/ProductConfig.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/application/controller/ProductController.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/application/controller/ProductRegistController.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/application/dto/ProductRegistDTO.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/application/service/ProductService.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/domain/aggregate/ProductRegist.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/domain/repository/ProductRepository.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/domain/repository/ex
  core-service/src/main/java/com/microsoftwo/clother/product/command/domain/service/ProductService.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/domain/service/ex
  core-service/src/main/java/com/microsoftwo/clother/product/query/controller/ProductController.java
  core-service/src/main/resources/com/microsoftwo/clother/product/query/repository/ProductMapper.xml
Labels: 🚘 feature

#29 [feat] 이메일 인증, 회원가입, 로그인 구현
  user-server/.gitattributes
  user-server/.gitignore
  user-server/build.gradle
  user-server/gradle/wrapper/gradle-wrapper.jar
  user-server/gradle/wrapper/gradle-wrapper.properties
  user-server/gradlew
  user-server/gradlew.bat
  user-server/settings.gradle
  user-server/src/main/java/com/microsoftwo/clother/HMACKeyGenerator.java
  user-server/src/main/java/com/microsoftwo/clother/UserServerApplication.java
  user-server/src/main/java/com/microsoftwo/clother/email/config/EmailConfig.java
  user-server/src/main/java/com/microsoftwo/clother/email/config/RedisConfig.java
  user-server/src/main/java/com/microsoftwo/clother/email/config/RedisUtil.java
  user-server/src/main/java/com/microsoftwo/clother/email/controller/EmailController.java
  user-server/src/main/java/com/microsoftwo/clother/email/dto/EmailCheckDTO.java
  user-server/src/main/java/com/microsoftwo/clother/email/exception/CustomException.java
  user-server/src/main/java/com/microsoftwo/clother/email/exception/GlobalExceptionHandler.java
  user-server/src/main/java/com/microsoftwo/clother/email/service/EmailService.java
  user-server/src/main/java/com/microsoftwo/clother/email/service/EmailServiceImpl.java
  user-server/src/main/java/com/microsoftwo/clother/email/vo/EmailRequestVO.java
  user-server/src/main/java/com/microsoftwo/clother/security/aggregate/RefreshToken.java
  user-server/src/main/java/com/microsoftwo/clother/security/config/CorsConfig.java
  user-server/src/main/java/com/microsoftwo/clother/security/config/SecurityConfig.java
  user-server/src/main/java/com/microsoftwo/clother/security/dto/TokenDTO.java
  user-server/src/main/java/com/microsoftwo/clother/security/jwt/JwtAccessDeniedHandler.java
  user-server/src/main/java/com/microsoftwo/clother/security/jwt/JwtAuthenticationEntryPoint.java
  user-server/src/main/java/com/microsoftwo/clother/security/jwt/JwtFilter.java
  user-server/src/main/java/com/microsoftwo/clother/security/jwt/TokenProvider.java
  user-server/src/main/java/com/microsoftwo/clother/security/repository/RefreshTokenRepository.java
  user-server/src/main/java/com/microsoftwo/clother/security/service/AuthService.java
  user-server/src/main/java/com/microsoftwo/clother/security/service/CustomUserDetailsService.java
  user-server/src/main/java/com/microsoftwo/clother/security/util/SecurityUtil.java
  user-server/src/main/java/com/microsoftwo/clother/security/vo/LoginRequestVO.java
  user-server/src/main/java/com/microsoftwo/clother/security/vo/LoginResponseVO.java
  user-server/src/main/java/com/microsoftwo/clother/security/vo/TokenRequestVO.java
  user-server/src/main/java/com/microsoftwo/clother/user/aggregate/Role.java
  user-server/src/main/java/com/microsoftwo/clother/user/aggregate/UserEntity.java
  user-server/src/main/java/com/microsoftwo/clother/user/config/AppConfig.java
  user-server/src/main/java/com/microsoftwo/clother/user/controller/UserController.java
  user-server/src/main/java/com/microsoftwo/clother/user/dto/UserDTO.java
  user-server/src/main/java/com/microsoftwo/clother/user/repository/UserRepository.java
  user-server/src/main/java/com/microsoftwo/clother/user/service/UserService.java
  user-server/src/main/java/com/microsoftwo/clother/user/service/UserServiceImpl.java
  user-server/src/main/java/com/microsoftwo/clother/user/vo/SignupRequestVO.java
  user-server/src/main/java/com/microsoftwo/clother/user/vo/SignupResponseVO.java
  user-server/src/test/java/com/microsoftwo/clother/UserServerApplicationTests.java
Labels: 🚘 feature

#36 [feat] 사용자의 상품 등록 내역 수정 구현
  core-service/src/main/java/com/microsoftwo/clother/product/command/application/controller/ProductRegistController.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/domain/aggregate/ProductRegist.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/domain/service/ProductService.java
Labels: 🚘 feature

#43 [feat] UserEntity id 타입 변경
  user-server/src/main/java/com/microsoftwo/clother/user/aggregate/UserEntity.java
Labels: 🐛 fix

#38 [feat] 게시물 등록 기능
  core-service/src/main/java/com/microsoftwo/clother/adviceBoard/command/application/controller/BoardCommandController.java
  core-service/src/main/java/com/microsoftwo/clother/adviceBoard/command/application/dto/BoardRequestDTO.java
  core-service/src/main/java/com/microsoftwo/clother/adviceBoard/command/application/service/BoardCommandService.java
  core-service/src/main/java/com/microsoftwo/clother/adviceBoard/command/application/service/BoardCommandServiceImpl.java
  core-service/src/main/java/com/microsoftwo/clother/adviceBoard/command/domain/aggregate/BoardEntity.java
  core-service/src/main/java/com/microsoftwo/clother/adviceBoard/command/domain/aggregate/ImageEntity.java
  core-service/src/main/java/com/microsoftwo/clother/adviceBoard/command/domain/repository/BoardCommandRepository.java
  core-service/src/main/java/com/microsoftwo/clother/adviceBoard/command/domain/repository/ImageRepository.java
  core-service/src/main/java/com/microsoftwo/clother/adviceBoard/command/infrastructure/service/ex
Labels: 🚘 feature

#32 [feat] post, post_image, tag insert
  core-service/src/main/java/com/microsoftwo/clother/post/command/application/controller/CommandPostController.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/application/controller/ex
  core-service/src/main/java/com/microsoftwo/clother/post/command/application/dto/ex
  core-service/src/main/java/com/microsoftwo/clother/post/command/application/service/CommandPostService.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/application/service/CommandPostServiceImpl.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/application/service/ex
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/aggregate/HairTagEntity.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/aggregate/PostEntity.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/aggregate/PostImageEntity.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/aggregate/TagEntity.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/aggregate/ex
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/repository/HairTagRepository.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/repository/PostImageRepository.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/repository/PostRepository.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/repository/TagRepository.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/repository/ex
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/service/ex
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/vo/HairTagVO.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/vo/PostImageVO.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/vo/ProductTagVO.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/domain/vo/RequestRegistPostVO.java
  core-service/src/main/java/com/microsoftwo/clother/post/command/infrastructure/service/ex
  core-service/src/main/java/com/microsoftwo/clother/post/query/controller/QueryPostController.java
  core-service/src/main/java/com/microsoftwo/clother/post/query/dao/QueryPostMapper.java
  core-service/src/main/java/com/microsoftwo/clother/post/query/service/QueryPostService.java
  core-service/src/main/java/com/microsoftwo/clother/post/query/service/QueryPostServiceImpl.java
  core-service/src/main/java/com/microsoftwo/clother/user/command/application/controller/ex
  core-service/src/main/java/com/microsoftwo/clother/user/command/application/dto/ex
  core-service/src/main/java/com/microsoftwo/clother/user/command/application/service/ex
  core-service/src/main/java/com/microsoftwo/clother/user/command/domain/aggregate/ex
  core-service/src/main/java/com/microsoftwo/clother/user/command/domain/repository/ex
  core-service/src/main/java/com/microsoftwo/clother/user/command/domain/service/ex
  core-service/src/main/java/com/microsoftwo/clother/user/command/infrastructure/service/ex
  core-service/src/main/java/com/microsoftwo/clother/user/query/controller/ex
  core-service/src/main/java/com/microsoftwo/clother/user/query/dao/ex
  core-service/src/main/java/com/microsoftwo/clother/user/query/service/ex
  core-service/src/main/resources/com/microsoftwo/clother/post/query/dao/QueryPostMapper.xml
Labels: 🚘 feature

#37 [feat] 사용자 상품 등록 내역 삭제 기능 구현
  core-service/src/main/java/com/microsoftwo/clother/product/command/application/controller/ProductRegistController.java
  core-service/src/main/java/com/microsoftwo/clother/product/command/domain/service/ProductService.java
Labels: 🚘 feature

#51 [feat] 사용자 댓글 삭제 기능 추가
  core-service/src/main/java/com/microsoftwo/clother/comment/command/application/controller/CommentRegistController.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/application/dto/CommentDTO.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/application/service/CommentService.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/domain/aggregate/Comment.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/domain/repository/CommentRepository.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/infrastructure/service/ex
  core-service/src/main/java/com/microsoftwo/clother/config/CommentConfig.java
  core-service/src/main/java/com/microsoftwo/clother/config/LikesConfig.java
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/controller/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/dto/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/service/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/aggregate/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/repository/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/service/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/infrastructure/service/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/query/controller/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/query/dto/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/query/mapper/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/query/service/ex
Labels: 🚘 feature

#53 [feat] 사용자 댓글 등록 기능 추가
  core-service/src/main/java/com/microsoftwo/clother/comment/command/application/controller/CommentRegistController.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/application/dto/CommentDTO.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/application/service/CommentService.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/domain/aggregate/Comment.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/domain/repository/CommentRepository.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/infrastructure/service/ex
  core-service/src/main/java/com/microsoftwo/clother/config/CommentConfig.java
  core-service/src/main/java/com/microsoftwo/clother/config/LikesConfig.java
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/controller/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/dto/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/service/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/aggregate/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/repository/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/service/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/infrastructure/service/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/query/controller/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/query/dto/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/query/mapper/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/query/service/ex
Labels: 🚘 feature

#61 [feat] 사용자 좋아요 등록 기능 추가
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/controller/LikeRegistController.java
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/controller/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/dto/LikeDTO.java
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/dto/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/service/LikeService.java
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/service/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/aggregate/Like.java
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/aggregate/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/repository/LikeRepository.java
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/repository/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/domain/service/ex
  core-service/src/main/java/com/microsoftwo/clother/likes/command/infrastructure/service/ex
Labels: 🚘 feature

#57 [feat] 이메일 인증 화면 생성
  user-server/build.gradle
  user-server/src/main/java/com/microsoftwo/clother/email/service/EmailServiceImpl.java
  user-server/src/main/java/com/microsoftwo/clother/security/config/SecurityConfig.java
  user-server/src/main/java/com/microsoftwo/clother/security/jwt/TokenProvider.java
  user-server/src/main/resources/email-template.html
Labels: 🚘 feature

#62 [feat] 사용자 좋아요 취소 기능 구현
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/controller/LikeRegistController.java
  core-service/src/main/java/com/microsoftwo/clother/likes/command/application/service/LikeService.java
Labels: 🚘 feature

#54 [test] post feed 조회 테스트
  core-service/src/test/java/com/microsoftwo/clother/post/query/service/QueryPostServiceImplTest.java
Labels: 🛡️ test

#60 [feat] swagger 추가
  core-service/build.gradle
  core-service/src/main/java/com/microsoftwo/clother/config/SwaggerConfig.java
Labels: 🚘 feature

#68 [feat] 컨텐츠별 댓글 조회
  core-service/src/main/java/com/microsoftwo/clother/comment/query/controller/CommentController.java
  core-service/src/main/java/com/microsoftwo/clother/comment/query/dto/CommentDTO.java
  core-service/src/main/java/com/microsoftwo/clother/comment/query/mapper/CommentMapper.java
  core-service/src/main/java/com/microsoftwo/clother/comment/query/service/CommentService.java
  core-service/src/main/java/com/microsoftwo/clother/comment/query/service/CommentServiceImpl.java
  core-service/src/main/resources/com/microsoftwo/clother/comment/query/mapper/CommentMapper.xml
Labels: 🚘 feature

#72 [hotfix] 타입 수정
  core-service/src/main/java/com/microsoftwo/clother/comment/command/application/dto/CommentDTO.java
  core-service/src/main/java/com/microsoftwo/clother/comment/command/domain/aggregate/Comment.java
Labels: 🚨 hotfix

#76 [refactor] user-service swaager 추가, setDateExpire 수정
  user-server/build.gradle
  user-server/src/main/java/com/microsoftwo/clother/email/config/EmailConfig.java
  user-server/src/main/java/com/microsoftwo/clother/email/config/RedisConfig.java
  user-server/src/main/java/com/microsoftwo/clother/email/config/RedisUtil.java
  user-server/src/main/java/com/microsoftwo/clother/email/controller/EmailController.java
  user-server/src/main/java/com/microsoftwo/clother/email/exception/CustomException.java
  user-server/src/main/java/com/microsoftwo/clother/email/service/EmailServiceImpl.java
  user-server/src/main/java/com/microsoftwo/clother/security/config/SecurityConfig.java
  user-server/src/main/java/com/microsoftwo/clother/security/jwt/JwtFilter.java
  user-server/src/main/java/com/microsoftwo/clother/security/jwt/TokenProvider.java
  user-server/src/main/java/com/microsoftwo/clother/security/service/AuthService.java
  user-server/src/main/java/com/microsoftwo/clother/user/controller/UserController.java
  user-server/src/main/java/com/microsoftwo/clother/user/dto/UserDTO.java
  user-server/src/main/java/com/microsoftwo/clother/user/service/UserService.java
  user-server/src/main/java/com/microsoftwo/clother/user/service/UserServiceImpl.java
Labels: 🏠 refactor

#79 [refactor] swagger 관련 수정
  user-server/build.gradle
  user-server/src/main/java/com/microsoftwo/clother/UserServerApplication.java
  user-server/src/main/java/com/microsoftwo/clother/security/config/SecurityConfig.java
  user-server/src/main/java/com/microsoftwo/clother/user/config/SwaggerConfig.java
Labels: 🚨 hotfix, 🏠 refactor

#81 [feat] token에 userId 추가
  user-server/src/main/java/com/microsoftwo/clother/security/dto/TokenDTO.java
  user-server/src/main/java/com/microsoftwo/clother/security/jwt/TokenProvider.java
  user-server/src/main/java/com/microsoftwo/clother/security/service/AuthService.java
Labels: 🚘 feature
